data1=read.table('household_power_consumption.txt',sep=';',header=TRUE,stringsAsFactors=FALSE)
head(data1)
data1$Date=as.Date(data1$Date,format='%d/%m/%Y')
data2=rbind(data1[(data1$Date=='2007-02-01'),],data1[(data1$Date=='2007-02-02'),])
head(data2)
data2$Global_active_power=as.numeric(data2$Global_active_power)
data2$Days=weekdays(data2$Date)
data2$Time1=strptime(paste(data2$Days,data2$Date,data2$Time),format='%a %Y-%m-%d %H:%M:%S')
plot(data2$Time1,data2$Sub_metering_1, type = "l",ylab='Energy sub metering',main=NA,xlab=NA)
lines(data2$Time1,data2$Sub_metering_2,col='red')
lines(data2$Time1,data2$Sub_metering_3,col='blue')
legend('topright',c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),lty=1,col=c('black','red','blue'),cex=0.6,y.intersp=0.6)
