data1=read.table('household_power_consumption.txt',sep=';',header=TRUE,stringsAsFactors=FALSE)
head(data1)
data1$Date=as.Date(data1$Date,format='%d/%m/%Y')
data2=rbind(data1[(data1$Date=='2007-02-01'),],data1[(data1$Date=='2007-02-02'),])
head(data2)
data2$Global_active_power=as.numeric(data2$Global_active_power)
data2$Days=weekdays(data2$Date)
data2$Time1=strptime(paste(data2$Days,data2$Date,data2$Time),format='%a %Y-%m-%d %H:%M:%S')
plot(data2$Time1,data2$Global_active_power, type = "l",ylab='Global Active Power (kilowatts)',main=NA,xlab=NA)
